# LAB 4


In [1]:
import pandas as pd
import numpy as np
import random
from IPython.display import Image
np.set_printoptions(precision = 3)

Load the data

In [7]:
data = pd.read_csv("jester-data-1.csv",header = None)

Erase the frist colum of the data

In [8]:
data = data.drop(columns=[0])
data.head()
print (data)

         1      2      3      4     5      6     7     8      9      10   \
0      -7.82   8.79  -9.66  -8.16 -7.52  -8.50 -9.85  4.17  -8.98  -4.76   
1       4.08  -0.29   6.36   4.37 -2.38  -9.66 -0.73 -5.34   8.88   9.22   
2      99.00  99.00  99.00  99.00  9.03   9.27  9.03  9.27  99.00  99.00   
3      99.00   8.35  99.00  99.00  1.80   8.16 -2.82  6.21  99.00   1.84   
4       8.50   4.61  -4.17  -5.39  1.36   1.60  7.04  4.61  -0.44   5.73   
5      -6.17  -3.54   0.44  -8.50 -7.09  -4.32 -8.69 -0.87  -6.65  -1.80   
6      99.00  99.00  99.00  99.00  8.59  -9.85  7.72  8.79  99.00  99.00   
7       6.84   3.16   9.17  -6.21 -8.16  -1.70  9.27  1.41  -5.19  -4.42   
8      -3.79  -3.54  -9.42  -6.89 -8.74  -0.29 -5.29 -8.93  -7.86  -1.60   
9       3.01   5.15   5.15   3.01  6.41   5.15  8.93  2.52   3.01   8.16   
10     -2.91   4.08  99.00  99.00 -5.73  99.00  2.48 -5.29  99.00   1.46   
11      1.31   1.80   2.57  -2.38  0.73   0.73 -0.97  5.00  -7.23  -1.36   
12     99.00

Save a copy of the original data

In [13]:
old_data = data.copy()
old_data.head()

1      2      3      4     5     6     7     8      9      10   ...    \
0  -7.82   8.79  -9.66  -8.16 -7.52 -8.50 -9.85  4.17  -8.98  -4.76  ...     
1   4.08  -0.29   6.36   4.37 -2.38 -9.66 -0.73 -5.34   8.88   9.22  ...     
2  99.00  99.00  99.00  99.00  9.03  9.27  9.03  9.27  99.00  99.00  ...     
3  99.00   8.35  99.00  99.00  1.80  8.16 -2.82  6.21  99.00   1.84  ...     
4   8.50   4.61  -4.17  -5.39  1.36  1.60  7.04  4.61  -0.44   5.73  ...     

     91     92     93     94     95     96     97     98     99     100  
0   2.82  99.00  99.00  99.00  99.00  99.00  -5.63  99.00  99.00  99.00  
1   2.82  -4.95  -0.29   7.86  -0.19  -2.14   3.06   0.34  -4.32   1.07  
2  99.00  99.00  99.00   9.08  99.00  99.00  99.00  99.00  99.00  99.00  
3  99.00  99.00  99.00   0.53  99.00  99.00  99.00  99.00  99.00  99.00  
4   5.19   5.58   4.27   5.19   5.73   1.55   3.11   6.55   1.80   1.60  

[5 rows x 100 columns]

Select the data to be working with


In [14]:
old_short_data = old_data [:120].copy()
old_short_data = old_short_data.values
new_data = data [:120].copy()
new_data = new_data.values

In [19]:
print(new_data)

[[-7.82  8.79 -9.66 ... 99.   99.   99.  ]
 [ 4.08 -0.29  6.36 ...  0.34 -4.32  1.07]
 [99.   99.   99.   ... 99.   99.   99.  ]
 ...
 [ 4.22  4.22 -3.59 ... 99.   99.   99.  ]
 [ 8.93  8.93  5.24 ... -8.59  0.53  7.28]
 [ 5.29  6.6  99.   ... 99.   99.   99.  ]]


Label 10% of the data cells as 99

In [26]:
#Label 10% of the dataset cells as 99


amount = 252318
a =0
count = 0
for i in range(0,100):
        for j in range(0,120):
            a = a + 1
            if count < amount:
                if a == 7:
                    a = 0
                    new_data[j][i] = 99
print(new_data)



[[-7.82  8.79 -9.66 ... 99.   99.   99.  ]
 [ 4.08 -0.29  6.36 ...  0.34 -4.32  1.07]
 [99.   99.   99.   ... 99.   99.   99.  ]
 ...
 [ 4.22 99.   -3.59 ... 99.   99.   99.  ]
 [99.    8.93  5.24 ... -8.59 99.    7.28]
 [ 5.29  6.6  99.   ... 99.   99.   99.  ]]


Prepare the information for the training

In [27]:
n_features = 2

user_ratings = new_data
latent_user_preferences = np.random.random((user_ratings.shape[0], n_features))
latent_item_features = np.random.random((user_ratings.shape[1],n_features))


In [28]:
def predict_rating(user_id,item_id):
    """ Predict a rating given a user_id and an item_id.
    """
    user_preference = latent_user_preferences[user_id]
    item_preference = latent_item_features[item_id]
    return user_preference.dot(item_preference)

def train(user_id, item_id, rating,alpha = 0.001):
    prediction_rating = predict_rating(user_id, item_id)
    err =  ( prediction_rating - rating );
    user_pref_values = latent_user_preferences[user_id][:]
    latent_user_preferences[user_id] -= alpha * err * latent_item_features[item_id]
    latent_item_features[item_id] -= alpha * err * user_pref_values
    return err

def test(user_id, item_id, rating,alpha = 0.001):
    prediction_rating = predict_rating(user_id, item_id)
    err_test =  ( prediction_rating - rating );
    return err_test



def sgd(iterations = 3000):
    """ Iterate over all users and all items and train for 
        a certain number of iterations
    """
    for iteration in range(0,iterations):
        error = []
        error_test=[]
        for user_id in range(0,latent_user_preferences.shape[0]):
            for item_id in range(0,latent_item_features.shape[0]):
                rating = user_ratings[user_id][item_id]
                rating_test = old_short_data[user_id][item_id]
                # We check if the value is not 99
                if(rating != 99 ):
                    err = train(user_id,item_id,rating)
                    error.append(err)
                if(rating_test != 99 ):
                    err_test = test(user_id,item_id,rating_test)
                    error_test.append(err_test)
        mse = (np.array(error) ** 2).mean()
        mse_test = (np.array(error_test) ** 2).mean()
        if(iteration%100 == 0 ):
            print ("mse in the train iteration",iteration,"is",mse)
            print ("mse in the test iteration",iteration,"is",mse_test)
    print("Final train mse", mse)
    print("Final test mse", mse_test)

In [29]:
sgd()

mse in the train iteration 0 is 27.27440649861577
mse in the test iteration 0 is 27.107319963445352
mse in the train iteration 100 is 17.07439394887514
mse in the test iteration 100 is 17.01238333855362
mse in the train iteration 200 is 17.07405422334968
mse in the test iteration 200 is 17.006646818514554
mse in the train iteration 300 is 17.07952280243048
mse in the test iteration 300 is 17.000891496384014
mse in the train iteration 400 is 17.087095204414194
mse in the test iteration 400 is 16.992928325123184
mse in the train iteration 500 is 17.09691348404797
mse in the test iteration 500 is 16.982661312967245
mse in the train iteration 600 is 17.109121592285703
mse in the test iteration 600 is 16.969892547817437
mse in the train iteration 700 is 17.123888079768626
mse in the test iteration 700 is 16.95436907458065
mse in the train iteration 800 is 17.141408933463744
mse in the test iteration 800 is 16.93578295050478
mse in the train iteration 900 is 17.161908628861223
mse in the tes

Show the predictions


In [30]:
predictions = latent_user_preferences.dot(latent_item_features.T)
predictions

array([[-2.726, -1.155, -3.005, ...,  0.777, -2.898,  2.448],
       [ 2.161,  1.524,  2.221, ...,  0.279,  2.175, -0.064],
       [ 7.335,  6.197,  7.268, ...,  2.456,  7.174,  2.946],
       ...,
       [-0.415, -0.215, -0.447, ...,  0.061, -0.433,  0.252],
       [ 0.638,  0.946,  0.524, ...,  0.814,  0.542,  1.514],
       [ 0.908,  1.953,  0.586, ...,  2.05 ,  0.649,  4.025]])

Create a comparison between the data and the predicted data

In [32]:
values = [zip(old_short_data[i], predictions[i]) for i in range(0,predictions.shape[0])]
comparison_data = pd.DataFrame(values)
comparison_data.columns = old_data.columns
#comparison_data.applymap(lambda (x,y): "(%2.3f|%2.3f)"%(x,y))

In [33]:
comparison_data

1                              2    \
0    (-7.82, -2.7260681623075493)    (8.79, -1.1552687563061714)   
1      (4.08, 2.1610791577106627)    (-0.29, 1.5238335337227973)   
2      (99.0, 7.3350716240506095)      (99.0, 6.197333163722501)   
3      (99.0, 0.9055204361635494)      (8.35, 1.026473762240461)   
4        (8.5, 3.593672351342035)     (4.61, 3.3763280663987887)   
5      (-6.17, -4.20656915844984)   (-3.54, -3.5903755700046487)   
6       (99.0, 4.048651611556634)      (99.0, 3.833662457545654)   
7      (6.84, -2.620768399121503)    (3.16, -1.7494625818439014)   
8    (-3.79, -0.5844919076223656)   (-3.54, 0.11150395175798344)   
9       (3.01, 3.594455473411978)      (5.15, 3.211656378377838)   
10     (-2.91, 3.772310215927056)     (4.08, 3.7816198521982223)   
11     (1.31, 1.7239694583224927)      (1.8, 2.0525715646739275)   
12      (99.0, 5.095278855979385)      (99.0, 4.949454460358568)   
13      (9.22, 4.494434848950519)      (9.27, 4.584021880936015)   
14   (8.79, -0.08402084190416292)  (-5.78, -0.46411281990375375)   
15    (-3.5, -0.6949645975495173)    (1.55, 0.21055695637905858)   
16      (99.0, 2.209721548277645)     (-9.27, 2.483449379865477)   
17     (3.16, 4.2311910980560175)      (7.62, 4.036014903306947)   
18     (4.22, 1.0057366095694822)     (3.64, 0.5374214431514305)   
19    (99.0, -0.9086469406739208)    (7.62, 0.02062654314957224)   
20    (2.57, -0.5833958494369806)  (-0.73, -0.12542123546841888)   
21     (7.28, 0.5054751668730206)     (5.39, 0.4164167707188977)   
22     (2.72, 1.6433979976611834)     (4.17, 1.9785043423367052)   
23      (2.09, 4.244618814417189)     (-7.57, 4.296121177674712)   
24     (-3.93, 1.050966533415053)    (-1.17, 1.1832849863959762)   
25      (99.0, 2.490644566457155)     (5.49, 2.5398846039454863)   
26     (99.0, 1.4173934090951648)     (5.83, 1.4773568419497365)   
27    (0.49, -1.8742742410158169)    (0.15, -0.8193374317771203)   
28     (99.0, 1.0758547048403875)     (99.0, 2.0016318789305396)   
29     (99.0, 2.4559969370686807)     (4.08, 2.2218995541045348)   
..                            ...                            ...   
90     (-3.16, 1.986340286632807)     (-1.12, 1.714285296706412)   
91     (99.0, 1.6929334752441028)     (-5.83, 2.372339765276577)   
92    (99.0, -0.8630773019356413)    (99.0, -0.5210638889791919)   
93    (-1.26, 3.6438511372037308)       (6.02, 3.26889034212806)   
94      (8.16, 4.643591673595033)     (2.28, 3.8992459718176717)   
95    (0.44, 0.17886185262225685)    (-8.45, 0.2674904935180798)   
96     (3.54, 0.2700700545867005)      (-5.0, 1.115829192405919)   
97     (99.0, 0.1532361350005616)    (99.0, -0.2027837023643655)   
98      (3.3, 2.0616358282019727)     (1.31, 2.0736906917653593)   
99     (99.0, -2.221497807431475)      (99.0, -1.78047812304987)   
100    (99.0, 3.1134251935636335)     (-8.5, 3.2743922650164192)   
101  (6.17, -0.20877224173312636)    (7.77, 0.19593874609577555)   
102     (5.68, -1.14659803855021)   (-2.86, -0.9572699459623608)   
103  (-1.89, -3.4800673633718664)   (-2.77, -2.9939226738021913)   
104    (-0.92, -4.24059958749241)   (-7.82, -3.7796586354118915)   
105    (99.0, 0.6398948479323538)    (-0.73, 2.0139663117121955)   
106   (3.45, -1.2024044350800855)   (-2.86, -0.6586752437432379)   
107   (-2.18, -1.121520682740734)    (-4.56, -0.765848643849607)   
108    (5.39, 1.8273055624549974)     (-2.57, 1.660927430248016)   
109     (3.11, 5.923753181949609)     (-2.77, 4.925354763460405)   
110   (3.06, -0.7367925804228471)   (0.87, -0.23601993018558354)   
111     (99.0, 4.669926649056058)      (5.73, 4.532707218197356)   
112    (2.38, -1.192731942984037)    (1.65, -1.2774918443593468)   
113   (99.0, -0.8393099417462664)    (99.0, 0.12937013097939576)   
114    (4.61, 1.5770440351021886)      (1.6, 1.9844052385898263)   
115   (-5.0, -1.5848375998627684)     (8.83, -0.459547114375656)   
116     (99.0, 1.017555167566068)     (99.0, 1.1578692090576699)   
117   (4.22, -0.41